# Generated by Django 4.2.21 on 2025-05-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='default_slug', max_length=100, verbose_name='Слаг'),
        ),
    ]
